/**
 * Reconstruct the Supabase schema as runnable DDL.
 *
 * Context: the source database is Wegic-hosted and unreachable over Postgres
 * (5432/6543 filtered, verified 2026-09-15), so pg_dump was never an option.
 * Column names, types, primary keys and NOT NULL come from PostgREST's own
 * OpenAPI spec, which is authoritative for those.
 *
 * What the spec does NOT carry — and where each replacement comes from:
 *   unique constraints  the `onConflict:` argument of every upsert in the
 *                       codebase. An upsert naming columns that carry no
 *                       unique index fails at runtime, so each onConflict is
 *                       direct evidence the constraint exists upstream.
 *   indexes             the .eq()/.order()/range filters the code actually
 *                       issues against each table.
 *   identity columns    only three tables use a numeric sequence; the rest
 *                       key on text (signals.id is "bt_1_MSTR_...", not a
 *                       number) and must accept explicit values on insert.
 *
 * Both are listed explicitly below rather than inferred at runtime, so a
 * reviewer can check each one against the source instead of trusting a
 * heuristic.
 */
import fs from 'node:fs';

const specPath = process.argv[2];
const outPath = process.argv[3];
if (!specPath || !outPath) {
  console.error('usage: generate-schema.mjs <openapi.json> <out.sql>');
  process.exit(1);
}
const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
const defs = spec.definitions || {};

/** Tables whose `id` is a real numeric sequence. Everything else supplies its own key. */
const IDENTITY_TABLES = new Set(['signal_outcomes', 'gex_regime_log', 'engine_shadow_signals']);

/** From `onConflict:` in the codebase — each implies a unique index upstream. */
const UNIQUE = {
  bars_1m:              ['ticker', 't_utc'],
  bars_daily:           ['ticker', 'date'],
  daily_high_low:       ['ticker', 'date'],
  earnings_calendar:    ['ticker', 'report_date'],
  financial_ratios:     ['ticker'],
  sec_filings_8k:       ['accession_number'],
  signal_outcomes:      ['signal_id', 'window_ms'],
  // The duplicate-signals fix (backups/signals-unique-constraint.sql).
  // Dropping this re-opens a bug that already required a row cleanup once.
  signals:              ['ticker', 'entry_tct', 'direction', 'signal_type'],
  stock_float:          ['ticker'],
};

/** Named exactly as upstream where the name is known, so later migrations match. */
const UNIQUE_NAME = { signals: 'signals_natural_key' };

/**
 * Columns that do not exist upstream and are added by this migration.
 *
 * pre_cvd_fix marks signals scored before CVD became session-scoped. Until
 * then cvdStore totalled from process boot, so the 25-point CVD factor was
 * reading days of stale flow (CLAUDE.md, "Fixed 2026-09-11"). Those rows are
 * a truthful record of what the system decided and are worth keeping — but
 * they must never feed a win rate unnoticed, so they are marked rather than
 * deleted. This mirrors the existing `pre_cooldown_fix` column, which the
 * codebase already uses for exactly this purpose.
 *
 * The boundary is NOT the fix's commit date. signals are written by the
 * BROWSER, and the browser fix (0f0758d) lives in this repo — which never
 * built the Wegic-hosted frontend. That code first served users at the Vercel
 * production deploy of f420df1, 2026-09-15T05:07:35.426Z. Every signal in the
 * source database predates it, so every migrated row is marked true.
 */
const EXTRA_COLUMNS = {
  signals: ['  "pre_cvd_fix" boolean not null default false'],
};

/** From the .eq()/.order()/range columns the code filters on. */
const INDEXES = {
  bars_1m:              [['ticker', 't_utc']],
  bars_daily:           [['ticker', 'date']],
  daily_high_low:       [['ticker', 'date']],
  insider_transactions: [['ticker', 'filing_date']],
  short_interest:       [['ticker', 'report_date']],
  short_volume:         [['ticker', 'trade_date']],
  sec_filings_8k:       [['filed_at']],
  signals:              [['status'], ['ticker'], ['entry_utc'], ['is_backtested']],
  signal_outcomes:      [['signal_id']],
  user_watchlist:       [['session_id'], ['added_at']],
  gex_regime_log:       [['ticker', 'observed_at'], ['session_date']],
  engine_shadow_signals:[['ticker', 'fired_at'], ['session_date']],
};

const q = (s) => `"${s}"`;

function columnSql(table, col, propSpec, required) {
  const type = propSpec.format || 'text';
  let line = `  ${q(col)} ${type}`;
  if (col === 'id' && IDENTITY_TABLES.has(table) && /int/.test(type)) {
    // "by default", never "always": the migration inserts the original ids so
    // signal_outcomes.signal_id keeps pointing at the right signals row.
    line += ' generated by default as identity';
  }
  if (required.includes(col)) line += ' not null';
  return line;
}

const out = [];
out.push('-- Reconstructed schema for the Helios Supabase project.');
out.push('-- Generated by backups/generate-schema.mjs — see that file for provenance.');
out.push(`-- Source spec: ${specPath}`);
out.push(`-- Generated:   ${new Date().toISOString()}`);
out.push('');
out.push('begin;');
out.push('');

const tables = Object.keys(defs).sort();
// signals before signal_outcomes: the FK depends on it.
tables.sort((a, b) => (a === 'signals' ? -1 : b === 'signals' ? 1 : 0));

for (const t of tables) {
  const def = defs[t];
  const props = def.properties || {};
  const required = def.required || [];
  const pks = Object.entries(props).filter(([, s]) => /<pk\/>/.test(s.description || '')).map(([c]) => c);

  out.push(`-- ${t}`);
  const cols = Object.entries(props).map(([c, s]) => columnSql(t, c, s, required));
  for (const extra of EXTRA_COLUMNS[t] || []) cols.push(extra);
  if (pks.length) cols.push(`  primary key (${pks.map(q).join(', ')})`);
  out.push(`create table if not exists public.${q(t)} (`);
  out.push(cols.join(',\n'));
  out.push(');');

  if (UNIQUE[t]) {
    const name = UNIQUE_NAME[t] || `${t}_unique`;
    out.push(`create unique index if not exists ${q(name)} on public.${q(t)} (${UNIQUE[t].map(q).join(', ')});`);
  }
  for (const idx of INDEXES[t] || []) {
    out.push(`create index if not exists ${q(`${t}_${idx.join('_')}_idx`)} on public.${q(t)} (${idx.map(q).join(', ')});`);
  }
  out.push('');
}

// signal_outcomes.signal_id -> signals.id, the one relationship the spec declares.
out.push('-- Declared relationship (the only one in the source spec)');
out.push(`alter table public."signal_outcomes"`);
out.push(`  drop constraint if exists signal_outcomes_signal_id_fkey;`);
out.push(`alter table public."signal_outcomes"`);
out.push(`  add constraint signal_outcomes_signal_id_fkey`);
out.push(`  foreign key ("signal_id") references public."signals"("id") on delete cascade;`);
out.push('');
out.push('commit;');
out.push('');

fs.writeFileSync(outPath, out.join('\n'));
console.log(`wrote ${outPath}`);
console.log(`tables: ${tables.length}`);
console.log(`unique constraints: ${Object.keys(UNIQUE).filter(t => defs[t]).length}`);
console.log(`indexed tables: ${Object.keys(INDEXES).filter(t => defs[t]).length}`);
